$color = rgba(11, 12, 12, 1)
$inner_color = rgba(11, 12, 12, 1)
$outer_color = rgba(67, 69, 73, 1)
$font_color = rgba(185, 185, 185, 1)
$placeholder_color = rgba(185, 185, 185, 0.7)
$check_color = rgba(237, 154, 29, 1)

general {
        grace = 10
        immediate_render = true
        hide_cursor = true
        ignore_empty_input = true
}

background {
           monitor =
           path = ~/.config/hypr/assets/wallpaper.jpg
           color = $color
           blur_passes = 3
}

# date
label {
      monitor =
      text = cmd[update:18000000] echo "<b> "$(date +'%A, %-d %B')" </b>"
      font_size = 48 
      font_family = Iosevka
      position = 0, -60
      halign = center
      valign = center
}

# user
label {
      monitor =
      text = $USER
      font_size = 36
      font_family = Iosevka
      position = 0, 275
      halign = center
      valign = bottom
}

# input field
input-field {
            monitor = 

            font_size = 36
            font_family = Iosevka
            font_color = $font_color

            size = 230, 70
            outline_thickness = 10
            dots_size = 0.3
            dots_spacing = 0.2
            dots_center = true
            fade_on_empty = false
            hide_input = false
            position = 0, 100
            halign = center
            valign = bottom
            check_color = $check_color

            inner_color = $inner_color
            outer_color = $outer_color
}

auth {
     fingerprint:enabled = true
}